language: node_js
node_js:
- '9'
# sudo: required
env:
  - CI=false # Stop warnings causing build failures
script:
  - cd public
  - npm install .
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: democracysausage.org
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"