version: "3.7"
services:
    # db:
    #     image: mdillon/postgis:10-alpine
    #     command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    #     # ports:
    #     #     - "5432:5432"
    #     environment:
    #         - POSTGRES_PASSWORD=postgres
    #         - POSTGRES_DB=stack
    #     volumes:
    #         # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
    #         - ./db/postgresql.conf:/etc/postgresql/postgresql.conf

    #         # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
    #         # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/

    #         # Enable this to store the PostgreSQL data on the host
    #         - ./db/data:/var/lib/postgresql/data
    php_api:
        image: php:7.1.25-cli-alpine3.8
        entrypoint: /app/sausage_api/docker-entrypoint.sh
        volumes:
            - ./php:/app/sausage_api:delegated
            - ./secrets/secrets.php:/app/secrets.php
            - ./db:/app/db:delegated
            - ./sentry-php:/app/sentry-php:delegated
            - ./google-api-php-client-2.2.0:/app/google-api-php-client-2.2.0:delegated
        environment:
            - ENVIRONMENT=PRODUCTION
    nginx_prod:
        image: sausage/nginx-prod:latest
        volumes:
            - ./keys/:/app/keys/:delegated
            - ./logs/nginx:/var/log/nginx:delegated
        depends_on:
            - django
        ports:
            - "443:443"
            - "444:444"
            - "8000:8000"
        environment:
            - HTTPS_ENABLED=TRUE
            - SERVER_NAME=localhost
            - DJANGO_LOCATION=django:8000
