version: "3.7"
services:
    db:
        image: mdillon/postgis:10-alpine
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=stack
        volumes:
            # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
            - ./db-pg/postgresql.conf:/etc/postgresql/postgresql.conf

            # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
            # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/

            # Enable this to store the PostgreSQL data on the host
            - ./db-pg/data:/var/lib/postgresql/data
    memcached:
        image: memcached:1.5-alpine
        expose:
            - "11211"
    django:
        build: django/
        entrypoint: /app/docker-entrypoint.sh
        volumes:
            - ./django/:/app:delegated
        ports:
            - "8000:8000"
        env_file:
            - secrets/sausage-web.dev.env
            - secrets/sausage-db.env
        depends_on:
            - db
            - memcached
    php_api:
        image: php:7.1.25-cli-alpine3.8
        entrypoint: /app/sausage_api/docker-entrypoint.sh
        volumes:
            - ./php:/app/sausage_api:delegated
            - ./secrets/secrets.php:/app/secrets.php
            - ./db:/app/db:delegated
            - ./sentry-php:/app/sentry-php:delegated
            - ./google-api-php-client-2.2.0:/app/google-api-php-client-2.2.0:delegated
        environment:
            - ENVIRONMENT=DEVELOPMENT
    frontend_public:
        image: node:10.14.2-alpine
        entrypoint: /app/docker-entrypoint.sh
        volumes:
            - ./public:/app:delegated
        env_file:
            - secrets/sausage-public-frontend.dev.env
    frontend_admin:
        image: node:10.14.2-alpine
        entrypoint: /app/docker-entrypoint.sh
        volumes:
            - ./admin:/app:delegated
        environment:
            - PORT=3001
        env_file:
            - secrets/sausage-admin-frontend.dev.env
    nginx:
        build: nginx/
        volumes:
            - ./nginx:/app
            - ./nginx/nginx/docker.https.dev.conf:/etc/nginx/conf.d/nginx.conf
            - ./keys/:/app/keys/:delegated
        depends_on:
            - django
            - php_api
            - frontend_public
            - frontend_admin
        ports:
            - "443:443"
            - "3001:3001"
            - "8001:8001"
            - "8003:8003"
